sudo: required
  
language: python

python:
    - 2.7

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev
            - libatlas-base-dev

install:
    - pip install \
        setuptools \
        numpy==1.13.3 \
        matplotlib==2.1.1 \
        scipy==0.19.1 \
        coveralls \
        codecov
    - pip install "lsl<1.3"
    - pip install "pylint<2.0"
    - pip install .

script:
    - cd tests
    - coverage run --source=lsl_toolkits.USRP -m unittest discover

after_success:
    - cd tests
    - coveralls
    - codecov
