sudo: required
  
language: python

python:
    - 2.7
    - 3.6

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev

install:
    - pip install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        coveralls \
        codecov
    - pip install git+https://github.com/lwa-project/lsl.git
    - pip install pylint
    - pip install .

script:
    - cd tests
    - coverage run --source=lsl_toolkits.USRP -m unittest discover

after_success:
    - cd tests
    - coveralls
    - codecov
