name: "Build and Test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['2.7', '3.6', '3.8']
      fail-fast: false
    steps:
      - name: "Software Install - Ubuntu"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            coreutils \
            curl \
            git \
            gpg \
            gpgv \
            gzip \
            libfftw3-dev \
            libgdbm-dev \
            pkg-config \
            software-properties-common
      - name: "Software Install - MacOS"
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install \
            fftw \
            pkg-config
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: "Software Install - Python" 
        run: |
          python -m pip install \
            setuptools \
            numpy \
            matplotlib \
            scipy \
            coveralls \
            coverage
          python -m pip install git+https://github.com/lwa-project/lsl.git
          python -m pip install pylint
      - name: "Build and Install"
        run: python -m pip install .
      - name: Test
        run: |
          cd tests
          coverage run --source=lsl_toolkits.USRP -m unittest discover
          coverage xml
      - name: "Upload Coverage"
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8' }}
        uses: codecov/codecov-action@v2
        with:
          directory: ./tests/
          fail_ci_if_error: false
          verbose: true
